In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
import glob
import torch
import torchvision 
import torchvision.transforms as transforms
from torchvision.transforms import v2
import shutil
import random

In [22]:
!pip install torch

In [4]:
#loops through images in a directory and makes 2 copies of every image, each with random color + affine modification
#all files in directory must be jpg image
#look out for hidden files (ls -a) (.DS_Store on mac ://///)
directory = '5xWSe2'
# iterate over files in 
# that directory
folders = os.listdir(directory)
for folder in folders:
    files = os.listdir(directory + "/" + folder)
    for image_name in files:
        print(directory)
        print(folder)
        print(image_name)
        image_path = directory + "/" + folder + "/" + image_name[:-3]
        image = cv2.imread(image_path + "jpg")
        print(image_path + "jpg")
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        toTensor = transforms.ToTensor()
        image = toTensor(image)
    
        color_change = v2.ColorJitter(brightness=.3, hue=.3)
        changed = color_change(image)
        affine = transforms.RandomAffine(degrees=(0,90), translate = (0.3,0.3), shear = (0,10,0,10))
        changed = affine(changed)
        torchvision.utils.save_image(changed, image_path + '1.jpg')
    
        color_change2 = v2.ColorJitter(brightness=.3, hue=.3)
        changed = color_change2(image)
        affine2 = transforms.RandomAffine(degrees=(0,90), translate = (0.3,0.3), shear = (-10,10,-10,10))
        changed = affine2(changed)
        torchvision.utils.save_image(changed, image_path + '2.jpg')
        

5xWSe2
08 11 2022
#3_03_5x.JPG
5xWSe2/08 11 2022/#3_03_5x.jpg
5xWSe2
08 11 2022
#1_04_5x.JPG
5xWSe2/08 11 2022/#1_04_5x.jpg
5xWSe2
08 11 2022
#3_02_5x.JPG
5xWSe2/08 11 2022/#3_02_5x.jpg
5xWSe2
02272022
s2_f3_5x.JPG
5xWSe2/02272022/s2_f3_5x.jpg
5xWSe2
02272022
s4_f1_5x.JPG
5xWSe2/02272022/s4_f1_5x.jpg
5xWSe2
02272022
s3_f5_5x.JPG
5xWSe2/02272022/s3_f5_5x.jpg
5xWSe2
02272022
s3_f3_5x.JPG
5xWSe2/02272022/s3_f3_5x.jpg
5xWSe2
02272022
s2_f7_5x.JPG
5xWSe2/02272022/s2_f7_5x.jpg
5xWSe2
02272022
s3_f1_5x.JPG
5xWSe2/02272022/s3_f1_5x.jpg
5xWSe2
02272022
s3_f4_5x.JPG
5xWSe2/02272022/s3_f4_5x.jpg
5xWSe2
02272022
s2_f2_5x.JPG
5xWSe2/02272022/s2_f2_5x.jpg
5xWSe2
02272022
f3_s1_5x.JPG
5xWSe2/02272022/f3_s1_5x.jpg
5xWSe2
02272022
s4_f2_5x.JPG
5xWSe2/02272022/s4_f2_5x.jpg
5xWSe2
02272022
s2_f8_5x.JPG
5xWSe2/02272022/s2_f8_5x.jpg
5xWSe2
02272022
s2_f4_5x.JPG
5xWSe2/02272022/s2_f4_5x.jpg
5xWSe2
02272022
s3_f2_5x.JPG
5xWSe2/02272022/s3_f2_5x.jpg
5xWSe2
02272022
s2_f6_5x.JPG
5xWSe2/02272022/s2_f6_5x.jpg
5x

In [5]:
#augment one folder
#loops through images in a directory and makes 2 copies of every image, each with random color + affine modification
#all files in directory must be jpg image
#look out for hidden files (ls -a) (.DS_Store on mac ://///)
directory = 'temp'
# iterate over files in 
# that directory
files = os.listdir(directory)
for image_name in files:
    image_path = directory + "/"  + image_name[:-3]
    #text_file = '../Downloads/monolayer_dataset2_v1/train/labels/' + image_name[:-3]
    image = cv2.imread(image_path + "jpg")
    print(image_path + "jpg")
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    toTensor = transforms.ToTensor()
    image = toTensor(image)
    
    color_change = v2.ColorJitter(brightness = .3, hue=.4)
    changed = color_change(image)
    affine = transforms.RandomAffine(degrees=(0,90), translate = (0.3,0.3), shear = (0,10,0,10))
    changed = affine(changed)
    torchvision.utils.save_image(changed, image_path + '1.jpg')

    
    color_change2 = v2.ColorJitter(brightness=.3, hue = .4)
    changed = color_change2(image)
    affine2 = transforms.RandomAffine(degrees=(0,90), translate = (0.3,0.3), shear = (-10,10,-10,10))
    changed = affine2(changed)
    torchvision.utils.save_image(changed, image_path + '2.jpg')

temp/C5_f2_x5.jpg
temp/C3_f2_x5.jpg
temp/C1_f1_x10.jpg
temp/#1_2_5x.jpg
temp/C7_f2_x5.jpg
temp/C5_f3_x5.jpg
temp/C5_f1_x5.jpg
temp/#1_3_5x.jpg
temp/C2_f1_x10.jpg
temp/C4_f1_x5.jpg
temp/#1_1_5x.jpg


In [ ]:
#crop one folder of images
#remember to remove .DS_Store!!!!!!!
new_height = 640
new_width = 640

directory = "null"
files = os.listdir(directory)
for image_name in files:
    image_path = directory + "/" + image_name
    image = cv2.imread(image_path)
    print(image_path)
    old_height = image.shape[0]
    old_width = image.shape[1]
    left = int((old_width - new_width)/2)
    right =int((old_width + new_width)/2)
    top = int((old_height - new_height)/2)
    bottom = int((old_height + new_height)/2)
    cropped = image[top:bottom, left:right]
    cv2.imwrite(image_path, cropped)
    cropped = cv2.cvtColor(cropped, cv2.COLOR_BGR2RGB)
    toTensor = transforms.ToTensor()
    image = toTensor(cropped)
    color_change = v2.ColorJitter(brightness=.3, hue=.4)
    changed = color_change(image)
    affine = transforms.RandomAffine(degrees=(0,90), translate = (0.3,0.3), shear = (0,10,0,10))
    changed = affine(changed)
    torchvision.utils.save_image(changed, image_path[:-3] + '1.jpg')#change
    color_change2 = v2.ColorJitter(brightness=.3, hue=.4)
    changed = color_change2(image)
    affine2 = transforms.RandomAffine(degrees=(0,90), translate = (0.3,0.3), shear = (-10,10,-10,10))
    changed = affine2(changed)
    torchvision.utils.save_image(changed, image_path[:-3] + '2.jpg')

In [ ]:
#crop and transform single image
new_width = 640
new_height = 640
file_name = "full row6/15.JPG"
image = cv2.imread(file_name)# change

old_height = image.shape[0]
old_width = image.shape[1]
left = int((old_width - new_width)/2)
right = int((old_width + new_width)/2)
top = int((old_height - new_height)/2)
bottom = int((old_height + new_height)/2)
image = image[top:bottom,left:right]#change cropping
cv2.imwrite(file_name, image)#change
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
toTensor = transforms.ToTensor()
image = toTensor(image)
color_change = v2.ColorJitter(brightness=.3, hue=.4)
changed = color_change(image)
affine = transforms.RandomAffine(degrees=(0,90), translate = (0.3,0.3), shear = (0,10,0,10))
changed = affine(changed)
torchvision.utils.save_image(changed, file_name[:-3] + '1.jpg')#change
color_change2 = v2.ColorJitter(brightness=.3, hue=.4)
changed = color_change2(image)
affine2 = transforms.RandomAffine(degrees=(0,90), translate = (0.3,0.3), shear = (-10,10,-10,10))
changed = affine2(changed)
torchvision.utils.save_image(changed, file_name[:-3] + '2.jpg')#change

In [ ]:
#Just crop photos (folders inside folder):
#remember to remove .DS_Store!
new_height = 1024
new_width = 1024

directory = "20ximages4"
folders = os.listdir(directory)
for folder in folders:
    files = os.listdir(directory + "/" + folder)
    for image_name in files:
        image_path = directory + "/" + folder + "/" + image_name
        image = cv2.imread(image_path)
        print(image_path)
        #image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        old_height = image.shape[0]
        old_width = image.shape[1]
        left = int((old_width - new_width)/2)
        right =int((old_width + new_width)/2)
        top = int((old_height - new_height)/2)
        bottom = int((old_height + new_height)/2)
        cropped = image[top:bottom, left:right]
        cv2.imwrite(image_path, cropped)

In [ ]:
#crop one image
new_width = 1024
new_height = 1024
image = cv2.imread("Images/MoSe2_09202023_07292024/02_20x.JPG")
old_height = image.shape[0]
old_width = image.shape[1]
left = int((old_width - new_width)/2)
right =int((old_width + new_width)/2)
top = int((old_height - new_height)/2)
bottom = int((old_height + new_height)/2)
cropped = image[0:1024, left:right]
cv2.imwrite("02_20x.JPG", cropped)

In [ ]:
#adjust one folder of images (no cropping)
directory = 'preprocessed'
# iterate over files in 
# that directory
folders = os.listdir(directory)
for folder in folders:
    files = os.listdir(directory + "/" + folder)
    for image_name in files:
        image_path = directory + "/" + folder + "/" + image_name[:-3]
        #text_file = '../Downloads/monolayer_dataset2_v1/train/labels/' + image_name[:-3]
        image = cv2.imread(image_path + "jpg")
        print(image_path + "jpg")
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        toTensor = transforms.ToTensor()
        image = toTensor(image)
        image = transforms.functional.adjust_hue(image, 0.1)
        torchvision.utils.save_image(image, image_path + 'jpg')
        color_change = v2.ColorJitter(brightness=.3, hue = None)
        changed = color_change(image)
        affine = transforms.RandomAffine(degrees=(0,90), translate = (0.3,0.3), shear = (0,10,0,10))
        changed = affine(changed)
        torchvision.utils.save_image(changed, image_path + '1.jpg')
        #txt1_path = text_file + "1.txt"
        #txt1 = open(txt1_path, "w")
        #shutil.copyfile(text_file + "txt", txt1_path)
        color_change2 = v2.ColorJitter(brightness=.3, hue = None)
        changed = color_change2(image)
        affine2 = transforms.RandomAffine(degrees=(0,90), translate = (0.3,0.3), shear = (-10,10,-10,10))
        changed = affine2(changed)
        torchvision.utils.save_image(changed, image_path + '2. jpg')

In [99]:
#goes through directory (yolov8 train, valid, or test), crops images by taking the center of the image and resizes the associated labels
new_height = 1024
new_width = 1024

directory = "../Downloads/20x2/train"
files = os.listdir(directory + "/images")

for image_name in files:
    #assumes folder in yolov8 format, where a folder has images and labels folder inside
    image_path = directory + "/images/" + image_name
    image = cv2.imread(image_path)
    old_height = image.shape[0]
    old_width = image.shape[1]
    left = int((old_width - new_width)/2)
    right =int((old_width + new_width)/2)
    top = int((old_height - new_height)/2)
    bottom = int((old_height + new_height)/2)
    cropped = image[top:bottom, left:right]
    cv2.imwrite(image_path, cropped)
    txt_path = directory + "/labels/" + image_name[:-3]+ "txt"
    file = open(txt_path, "r")
    print(file)
    boxes = file.readlines()
    print(boxes)
    for line in range(len(boxes)):
        print("Old:")
        print(boxes[line])
        numbers = boxes[line].split()
        #class_id center_x center_y width height - format of each line
        #calculate new numbers, write it into array
        old_center_x = float(numbers[1])
        old_center_y = float(numbers[2])
        old_w = float(numbers[3])
        old_h = float(numbers[4])
        new_center_x = float((old_center_x * old_width - left)/new_width)
        new_center_y = float((old_center_y * old_height - top)/new_height)
        if (new_center_x < 0 or new_center_y < 0 or new_center_x > 1 or new_center_y > 1):
            boxes[line] = ''
        else:
            height_scale = old_height/new_height
            width_scale = old_width/new_width
            new_h = old_h * height_scale
            new_w = old_w * width_scale
            if (new_center_x - new_w < 0):
                old_w = new_w
                old_centerx = new_center_x
                new_w = old_centerx + old_w/2
                new_center_x = new_w/2
            if (new_center_x + new_w > 1):
                old_w = new_w
                old_centerx = new_center_x
                new_w = 1-old_centerx + old_w/2
                new_center_x = (1 - new_w)/2
            if (new_center_y - new_h < 0):
                old_h = new_h
                old_centery = new_center_y
                new_h = old_centery + old_h/2
                new_center_y = new_h/2
            if (new_center_y + new_h > 1):
                old_h = new_h
                old_centery = new_center_y
                new_h = (1-old_centery) + old_h/2
                new_center_y = (1 - new_h)/2
            numbers[1] = str(new_center_x)
            numbers[2] = str(new_center_y)
            numbers[3] = str(new_w)
            numbers[4] = str(new_h)
            boxes[line] = numbers[0]+ " " + numbers[1] + " " + numbers[2] + " " + numbers[3] + " " + numbers[4]
            if len(boxes) > 1 and line < len(boxes) - 1:
                boxes[line] += '\n'
    file.close()
    file = open(txt_path, "w")
    file.writelines(boxes)
    file.close()
    #pull up the text file
    #write it
    

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/-1_10X_JPG.rf.b33d19a82454d4ade11f876a5f10b219.txt' mode='r' encoding='UTF-8'>
['0 0.5215767973856209 0.494052734375 0.01401143790849673 0.0037841796875\n', '0 0.5223080065359477 0.5023388671875 0.009158496732026145 0.00751953125']
Old:
0 0.5215767973856209 0.494052734375 0.01401143790849673 0.0037841796875

New:
['0', '0.5515820312499999', '0.48810546875000005', '0.03349609375', '0.007568359375']
['0 0.5515820312499999 0.48810546875000005 0.03349609375 0.007568359375\n', '0 0.5223080065359477 0.5023388671875 0.009158496732026145 0.00751953125']
Old:
0 0.5223080065359477 0.5023388671875 0.009158496732026145 0.00751953125
New:
['0', '0.5533300781249999', '0.504677734375', '0.02189453125', '0.0150390625']
['0 0.5515820312499999 0.48810546875000005 0.03349609375 0.007568359375\n', '0 0.5533300781249999 0.504677734375 0.02189453125 0.0150390625']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/flake1_10X-1_jpg.rf.12d778a86bb80

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/flake8_20X-2_jpg.rf.d44446a919b1d1dc9d160f06887bba3f.txt' mode='r' encoding='UTF-8'>
['0 0.630061274509804 0.6750390625 0.07487336601307189 0.022900390625\n', '0 0.7872549019607843 0.604716796875 0.03819035947712418 0.0169091796875\n', '0 0.8668668300653596 0.607177734375 0.028169934640522875 0.024345703125']
Old:
0 0.630061274509804 0.6750390625 0.07487336601307189 0.022900390625

New:
['0', '0.8109277343750001', '0.850078125', '0.178994140625', '0.04580078125']
['0 0.8109277343750001 0.850078125 0.178994140625 0.04580078125\n', '0 0.7872549019607843 0.604716796875 0.03819035947712418 0.0169091796875\n', '0 0.8668668300653596 0.607177734375 0.028169934640522875 0.024345703125']
Old:
0 0.7872549019607843 0.604716796875 0.03819035947712418 0.0169091796875

['0 0.8109277343750001 0.850078125 0.178994140625 0.04580078125\n', '', '0 0.8668668300653596 0.607177734375 0.028169934640522875 0.024345703125']
Old:
0 0.8668668300653596 0.607

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/38_20x-2_jpg.rf.5503fc84ecbb37f5dc924d2f09c9643b.txt' mode='r' encoding='UTF-8'>
['0 0.4411683006535948 0.4846484375 0.04378267973856209 0.1360107421875']
Old:
0 0.4411683006535948 0.4846484375 0.04378267973856209 0.1360107421875
New:
['0', '0.35935546875', '0.46929687499999995', '0.10466796875', '0.272021484375']
['0 0.35935546875 0.46929687499999995 0.10466796875 0.272021484375']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/null2_10x-2_jpg.rf.ddfda75bbb904521ebc3b06e0af3daaf.txt' mode='r' encoding='UTF-8'>
[]
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/4-5-6-7-8-9-10-11-10x_JPG.rf.3fcb81af4d8b96546bbbccc5a52318e2.txt' mode='r' encoding='UTF-8'>
['0 0.27293709150326795 0.3253759765625 0.033529411764705884 0.0249658203125\n', '0 0.2234517973856209 0.340185546875 0.013378267973856208 0.02259765625\n', '0 0.23125816993464052 0.3645166015625 0.015371732026143791 0.0101904296875\n', '0 0.181078431372549 0.334960

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/13-14_20x_JPG.rf.22c4a1db7dbbdea79d1271349ad7a6a6.txt' mode='r' encoding='UTF-8'>
['0 0.4074468954248366 0.6278466796875 0.01301470588235294 0.0115576171875\n', '0 0.5627124183006535 0.5149169921875 0.005302287581699347 0.00650390625']
Old:
0 0.4074468954248366 0.6278466796875 0.01301470588235294 0.0115576171875

New:
['0', '0.27874023437499995', '0.7556933593749999', '0.03111328125', '0.023115234375']
['0 0.27874023437499995 0.7556933593749999 0.03111328125 0.023115234375\n', '0 0.5627124183006535 0.5149169921875 0.005302287581699347 0.00650390625']
Old:
0 0.5627124183006535 0.5149169921875 0.005302287581699347 0.00650390625
New:
['0', '0.649921875', '0.529833984375', '0.01267578125', '0.0130078125']
['0 0.27874023437499995 0.7556933593749999 0.03111328125 0.023115234375\n', '0 0.649921875 0.529833984375 0.01267578125 0.0130078125']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/flake10_20X_1-1_jpg.rf.22114d8b923498f2438

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/flake7_20X_1_JPG.rf.5570ceb1981abe251571576b5603a34c.txt' mode='r' encoding='UTF-8'>
['0 0.5019485294117647 0.484140625 0.02360294117647059 0.030185546875']
Old:
0 0.5019485294117647 0.484140625 0.02360294117647059 0.030185546875
New:
['0', '0.504658203125', '0.46828125', '0.05642578125000001', '0.06037109375']
['0 0.504658203125 0.46828125 0.05642578125000001 0.06037109375']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/-01_01_10x-1_jpg.rf.2bbc2d90611598610c63e8ab26f71928.txt' mode='r' encoding='UTF-8'>
['0 0.40650735294117646 0.6381689453125 0.014003267973856209 0.02119140625\n', '0 0.39006127450980393 0.63515625 0.014950980392156863 0.0223388671875']
Old:
0 0.40650735294117646 0.6381689453125 0.014003267973856209 0.02119140625

New:
['0', '0.276494140625', '0.776337890625', '0.0334765625', '0.0423828125']
['0 0.276494140625 0.776337890625 0.0334765625 0.0423828125\n', '0 0.39006127450980393 0.63515625 0.01495098039215

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/01_5x_JPG.rf.8c2c9605c3ec5213a415eae752368909.txt' mode='r' encoding='UTF-8'>
['0 0.5475 0.3003857421875 0.009746732026143791 0.012998046875']
Old:
0 0.5475 0.3003857421875 0.009746732026143791 0.012998046875
New:
['0', '0.6135546875', '0.10077148437500005', '0.02330078125', '0.02599609375']
['0 0.6135546875 0.10077148437500005 0.02330078125 0.02599609375']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/18-19_20x-1_jpg.rf.2c14978031e49f56c12549225f6a56b4.txt' mode='r' encoding='UTF-8'>
['0 0.8709885620915032 0.9330078125 0.019987745098039217 0.016435546875']
Old:
0 0.8709885620915032 0.9330078125 0.019987745098039217 0.016435546875
['']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/16_10x-2_jpg.rf.4b2fc26e6cc76ef1afe40cce9691c5ce.txt' mode='r' encoding='UTF-8'>
['0 0.14083741830065358 0.670859375 0.019113562091503267 0.0150048828125']
Old:
0 0.14083741830065358 0.670859375 0.019113562091503267 0.0150048828125
['

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/05_20x_JPG.rf.001eb504514d9f39313f224cb14079cf.txt' mode='r' encoding='UTF-8'>
['0 0.6037622549019608 0.3624951171875 0.03400735294117647 0.049560546875\n', '0 0.6049428104575164 0.4183056640625 0.01113970588235294 0.038154296875\n', '0 0.5738235294117647 0.432109375 0.048799019607843136 0.034404296875']
Old:
0 0.6037622549019608 0.3624951171875 0.03400735294117647 0.049560546875

New:
['0', '0.748056640625', '0.224990234375', '0.081298828125', '0.09912109375']
['0 0.748056640625 0.224990234375 0.081298828125 0.09912109375\n', '0 0.6049428104575164 0.4183056640625 0.01113970588235294 0.038154296875\n', '0 0.5738235294117647 0.432109375 0.048799019607843136 0.034404296875']
Old:
0 0.6049428104575164 0.4183056640625 0.01113970588235294 0.038154296875

New:
['0', '0.7508789062500001', '0.33661132812500005', '0.026630859375', '0.07630859375']
['0 0.748056640625 0.224990234375 0.081298828125 0.09912109375\n', '0 0.7508789062500001 0.33

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/08_5x-1_jpg.rf.fd5663059e996b1198de5ae1847a992f.txt' mode='r' encoding='UTF-8'>
[]
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/16_10X-1_jpg.rf.d0084bcbc35891cf7b5608e24cbb4ed1.txt' mode='r' encoding='UTF-8'>
['0 0.6472916666666666 0.74044921875 0.015318627450980392 0.015263671875']
Old:
0 0.6472916666666666 0.74044921875 0.015318627450980392 0.015263671875
New:
['0', '0.8521191406249999', '0.017182617187499975', '0.03662109375', '0.03436523437499995']
['0 0.8521191406249999 0.017182617187499975 0.03662109375 0.03436523437499995']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/6-7-8_20x-1_jpg.rf.8385d9887229e0467c9fd5ef9e380d5e.txt' mode='r' encoding='UTF-8'>
['0 0.31812091503267975 0.8003564453125 0.03937908496732026 0.0691650390625\n', '0 0.2613153594771242 0.7029248046875 0.03638480392156863 0.0395703125\n', '0 0.36073937908496734 0.4901806640625 0.03243872549019608 0.046552734375']
Old:
0 0.3181209150326797

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/34_20x-1_jpg.rf.4c95eb8368bba649c0f46c1963c4704d.txt' mode='r' encoding='UTF-8'>
['0 0.3737990196078431 0.3106298828125 0.02269607843137255 0.029248046875']
Old:
0 0.3737990196078431 0.3106298828125 0.02269607843137255 0.029248046875
New:
['0', '0.19830078124999995', '0.12125976562499996', '0.0542578125', '0.05849609375']
['0 0.19830078124999995 0.12125976562499996 0.0542578125 0.05849609375']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/08_10x-1_jpg.rf.6bb641cbac159ce65b92daa85ad5bc57.txt' mode='r' encoding='UTF-8'>
['0 0.42262254901960783 0.6167919921875 0.016037581699346406 0.0234765625']
Old:
0 0.42262254901960783 0.6167919921875 0.016037581699346406 0.0234765625
New:
['0', '0.31501953124999993', '0.733583984375', '0.03833984375', '0.046953125']
['0 0.31501953124999993 0.733583984375 0.03833984375 0.046953125']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/22_10x-1_jpg.rf.65e6c8369677939bc0d1f8eab19405f6.t

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/flake5_10X-2_jpg.rf.5dfc7d81ecfbefea5fa10e8780f5c730.txt' mode='r' encoding='UTF-8'>
['0 0.3510294117647059 0.4759033203125 0.0058823529411764705 0.0165673828125']
Old:
0 0.3510294117647059 0.4759033203125 0.0058823529411764705 0.0165673828125
New:
['0', '0.14386718750000005', '0.451806640625', '0.0140625', '0.033134765625']
['0 0.14386718750000005 0.451806640625 0.0140625 0.033134765625']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/21_10x-2_jpg.rf.7e3e8d7aa17a860cc040fc8e073a657e.txt' mode='r' encoding='UTF-8'>
['0 0.3356372549019608 0.4921728515625 0.009995915032679738 0.0117724609375']
Old:
0 0.3356372549019608 0.4921728515625 0.009995915032679738 0.0117724609375
New:
['0', '0.10707031249999999', '0.484345703125', '0.023896484375', '0.023544921875']
['0 0.10707031249999999 0.484345703125 0.023896484375 0.023544921875']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/-01_06_10x-1_jpg.rf.731def1d8bc696654e2d24

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/02_5x-1_jpg.rf.aa5185209894c5fa4c3306d8552baa2a.txt' mode='r' encoding='UTF-8'>
['0 0.42590277777777774 0.5102587890625 0.018370098039215684 0.02287109375']
Old:
0 0.42590277777777774 0.5102587890625 0.018370098039215684 0.02287109375
New:
['0', '0.3228613281249999', '0.520517578125', '0.04391601562499999', '0.0457421875']
['0 0.3228613281249999 0.520517578125 0.04391601562499999 0.0457421875']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/07_5x_JPG.rf.d9b58fc26a4c9f989014c407dbced447.txt' mode='r' encoding='UTF-8'>
[]
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/-1_02_10x_JPG.rf.9ffbf3f1a8543053fcde4e726ed574c6.txt' mode='r' encoding='UTF-8'>
['0 0.4667565359477124 0.5431005859375 0.0073692810457516335 0.0224755859375']
Old:
0 0.4667565359477124 0.5431005859375 0.0073692810457516335 0.0224755859375
New:
['0', '0.4205273437499999', '0.586201171875', '0.0176171875', '0.044951171875']
['0 0.4205273437499999 0.58

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/51_20x-1_jpg.rf.fd87577eb23020e0183911647815973b.txt' mode='r' encoding='UTF-8'>
['0 0.5685294117647058 0.268046875 0.020829248366013072 0.0167822265625\n', '0 0.5705596405228758 0.2436572265625 0.033022875816993466 0.016630859375\n', '0 0.6064746732026144 0.1995751953125 0.030040849673202617 0.0197607421875']
Old:
0 0.5685294117647058 0.268046875 0.020829248366013072 0.0167822265625

New:
['0', '0.663828125', '0.036093750000000036', '0.049794921875', '0.033564453125']
['0 0.663828125 0.036093750000000036 0.049794921875 0.033564453125\n', '0 0.5705596405228758 0.2436572265625 0.033022875816993466 0.016630859375\n', '0 0.6064746732026144 0.1995751953125 0.030040849673202617 0.0197607421875']
Old:
0 0.5705596405228758 0.2436572265625 0.033022875816993466 0.016630859375

['0 0.663828125 0.036093750000000036 0.049794921875 0.033564453125\n', '', '0 0.6064746732026144 0.1995751953125 0.030040849673202617 0.0197607421875']
Old:
0 0.6064

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/25_10x-2_jpg.rf.c7a331523605a083dfadf15ca79f7a14.txt' mode='r' encoding='UTF-8'>
['0 0.30653594771241827 0.3612841796875 0.008754084967320261 0.012060546875\n', '0 0.421952614379085 0.42111328125 0.014268790849673203 0.01056640625\n', '0 0.40642565359477123 0.4720263671875 0.009133986928104574 0.0098486328125\n', '0 0.4149264705882353 0.486943359375 0.012798202614379084 0.013759765625']
Old:
0 0.30653594771241827 0.3612841796875 0.008754084967320261 0.012060546875

New:
['0', '0.03749999999999987', '0.22256835937499997', '0.020927734375', '0.02412109375']
['0 0.03749999999999987 0.22256835937499997 0.020927734375 0.02412109375\n', '0 0.421952614379085 0.42111328125 0.014268790849673203 0.01056640625\n', '0 0.40642565359477123 0.4720263671875 0.009133986928104574 0.0098486328125\n', '0 0.4149264705882353 0.486943359375 0.012798202614379084 0.013759765625']
Old:
0 0.421952614379085 0.42111328125 0.014268790849673203 0.01056640625

N

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/flake1_10X_JPG.rf.1c918b5e0510408c4d82021b07360008.txt' mode='r' encoding='UTF-8'>
['0 0.5142687908496733 0.5203857421875 0.009526143790849673 0.016240234375\n', '0 0.5250163398692811 0.523095703125 0.008488562091503268 0.0160302734375']
Old:
0 0.5142687908496733 0.5203857421875 0.009526143790849673 0.016240234375

New:
['0', '0.5341113281250001', '0.540771484375', '0.0227734375', '0.03248046875']
['0 0.5341113281250001 0.540771484375 0.0227734375 0.03248046875\n', '0 0.5250163398692811 0.523095703125 0.008488562091503268 0.0160302734375']
Old:
0 0.5250163398692811 0.523095703125 0.008488562091503268 0.0160302734375
New:
['0', '0.5598046875', '0.54619140625', '0.02029296875', '0.032060546875']
['0 0.5341113281250001 0.540771484375 0.0227734375 0.03248046875\n', '0 0.5598046875 0.54619140625 0.02029296875 0.032060546875']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/13_20x_JPG.rf.a767546965193ebd36e3eff90ad860c5.txt' mod

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/27_10x_JPG.rf.c0a7b2c7225d940fbb3c941a37f1ff7b.txt' mode='r' encoding='UTF-8'>
['0 0.48452614379084963 0.4978515625 0.011499183006535947 0.0256005859375']
Old:
0 0.48452614379084963 0.4978515625 0.011499183006535947 0.0256005859375
New:
['0', '0.4630078124999999', '0.495703125', '0.027490234375', '0.051201171875']
['0 0.4630078124999999 0.495703125 0.027490234375 0.051201171875']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/49_20x_JPG.rf.737e54cafb3832be417445e42c29a4d7.txt' mode='r' encoding='UTF-8'>
['0 0.5350204248366013 0.5111572265625 0.047973856209150324 0.018701171875']
Old:
0 0.5350204248366013 0.5111572265625 0.047973856209150324 0.018701171875
New:
['0', '0.583720703125', '0.5223144531249999', '0.1146875', '0.03740234375']
['0 0.583720703125 0.5223144531249999 0.1146875 0.03740234375']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/13_20x-1_jpg.rf.037fccaf1e4cef0a974889ed50563bfc.txt' mode='r' encodin

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/27_10x-2_jpg.rf.bb78121b1c96adba5e21c690407baec0.txt' mode='r' encoding='UTF-8'>
['0 0.5389297385620915 0.5080029296875 0.01994281045751634 0.0182763671875']
Old:
0 0.5389297385620915 0.5080029296875 0.01994281045751634 0.0182763671875
New:
['0', '0.59306640625', '0.5160058593750001', '0.04767578125', '0.036552734375']
['0 0.59306640625 0.5160058593750001 0.04767578125 0.036552734375']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/flake11_10X_JPG.rf.2d320ab2430c2b2e5dfa618d6098e322.txt' mode='r' encoding='UTF-8'>
['0 0.5136805555555556 0.5011865234375 0.029219771241830065 0.0358447265625']
Old:
0 0.5136805555555556 0.5011865234375 0.029219771241830065 0.0358447265625
New:
['0', '0.532705078125', '0.5023730468750001', '0.069853515625', '0.071689453125']
['0 0.532705078125 0.5023730468750001 0.069853515625 0.071689453125']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/17_20z_JPG.rf.84515437f3d038d3f054f72615d5d7f

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/30_20x_JPG.rf.8d05d7cdfcdaa922566cd2deb0f363e9.txt' mode='r' encoding='UTF-8'>
['0 0.5470057189542483 0.5519140625 0.03707924836601307 0.0211181640625']
Old:
0 0.5470057189542483 0.5519140625 0.03707924836601307 0.0211181640625
New:
['0', '0.6123730468749999', '0.6038281249999999', '0.088642578125', '0.042236328125']
['0 0.6123730468749999 0.6038281249999999 0.088642578125 0.042236328125']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/20_20x_JPG.rf.0066dd1ad2c7811a3253ce15229bc805.txt' mode='r' encoding='UTF-8'>
['0 0.5034313725490196 0.51525390625 0.010155228758169934 0.0124267578125']
Old:
0 0.5034313725490196 0.51525390625 0.010155228758169934 0.0124267578125
New:
['0', '0.5082031249999999', '0.5305078125', '0.024277343749999996', '0.024853515625']
['0 0.5082031249999999 0.5305078125 0.024277343749999996 0.024853515625']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/10_20x_JPG.rf.b4289f43b1471b16f89974a8ee7e

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/17_20z-1_jpg.rf.75fdf75a13d0de9a287e34c922ee9a4c.txt' mode='r' encoding='UTF-8'>
['0 0.5403431372549019 0.380888671875 0.012340686274509804 0.006298828125']
Old:
0 0.5403431372549019 0.380888671875 0.012340686274509804 0.006298828125
New:
['0', '0.5964453124999998', '0.26177734374999995', '0.029501953125', '0.01259765625']
['0 0.5964453124999998 0.26177734374999995 0.029501953125 0.01259765625']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/01_5x-1_jpg.rf.fb37b6d3e688dfae6a7d02707e63cccf.txt' mode='r' encoding='UTF-8'>
['0 0.5165277777777778 0.2665234375 0.00931781045751634 0.0125244140625']
Old:
0 0.5165277777777778 0.2665234375 0.00931781045751634 0.0125244140625
New:
['0', '0.53951171875', '0.03304687500000003', '0.022275390625000002', '0.025048828125']
['0 0.53951171875 0.03304687500000003 0.022275390625000002 0.025048828125']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/flake7_10X_1-2_jpg.rf.eb532dc839445

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/08_20x-2_jpg.rf.ce9eebb00d6632b1fcd1996fdcf559c7.txt' mode='r' encoding='UTF-8'>
['0 0.39625408496732023 0.4502099609375 0.04272875816993464 0.067041015625']
Old:
0 0.39625408496732023 0.4502099609375 0.04272875816993464 0.067041015625
New:
['0', '0.251982421875', '0.400419921875', '0.10214843750000001', '0.13408203125']
['0 0.251982421875 0.400419921875 0.10214843750000001 0.13408203125']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/39_10x-2_jpg.rf.08ecb53d41dba7aa53e127e5ca962918.txt' mode='r' encoding='UTF-8'>
['0 0.30650326797385624 0.2580419921875 0.02638480392156863 0.0185107421875']
Old:
0 0.30650326797385624 0.2580419921875 0.02638480392156863 0.0185107421875
New:
['0', '0.034479980468750025', '0.017297363281250012', '0.06895996093750005', '0.034594726562500025']
['0 0.034479980468750025 0.017297363281250012 0.06895996093750005 0.034594726562500025']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/07_20x

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/flake11_10X-2_jpg.rf.5807cb4749f866e5af8f67408c6a1db5.txt' mode='r' encoding='UTF-8'>
['0 0.6095138888888889 0.5131103515625 0.004093137254901961 0.005126953125']
Old:
0 0.6095138888888889 0.5131103515625 0.004093137254901961 0.005126953125
New:
['0', '0.7618066406250001', '0.5262207031249999', '0.00978515625', '0.01025390625']
['0 0.7618066406250001 0.5262207031249999 0.00978515625 0.01025390625']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/04_20x-2_jpg.rf.74197c9cf491ea6531d835b7a0cb5edd.txt' mode='r' encoding='UTF-8'>
['0 0.357140522875817 0.7065234375 0.011629901960784313 0.012470703125']
Old:
0 0.357140522875817 0.7065234375 0.011629901960784313 0.012470703125
New:
['0', '0.15847656249999997', '0.913046875', '0.027802734375', '0.02494140625']
['0 0.15847656249999997 0.913046875 0.027802734375 0.02494140625']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/25-26_10x-2_jpg.rf.db680b2ed5a9e58d2af17a6308bc1f9d

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/flake10_5X_1-1_jpg.rf.868fff5a3008878d71548746c730bdf1.txt' mode='r' encoding='UTF-8'>
['0 0.4002042483660131 0.237578125 0.003754084967320261 0.007822265625']
Old:
0 0.4002042483660131 0.237578125 0.003754084967320261 0.007822265625
['']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/05_10x-2_jpg.rf.d1c86fb2ea74b5354491517edd30bc1f.txt' mode='r' encoding='UTF-8'>
['0 0.6122630718954248 0.702470703125 0.022483660130718956 0.0169287109375\n', '0 0.5810702614379085 0.7238525390625 0.021813725490196077 0.018828125']
Old:
0 0.6122630718954248 0.702470703125 0.022483660130718956 0.0169287109375

New:
['0', '0.7683789062499999', '0.9049414062500001', '0.053750000000000006', '0.033857421875']
['0 0.7683789062499999 0.9049414062500001 0.053750000000000006 0.033857421875\n', '0 0.5810702614379085 0.7238525390625 0.021813725490196077 0.018828125']
Old:
0 0.5810702614379085 0.7238525390625 0.021813725490196077 0.018828125
New:
['0',

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/04_5x-2_jpg.rf.fb32c181f531c83eaf5ec8623a4555bb.txt' mode='r' encoding='UTF-8'>
[]
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/null2_20x-1_jpg.rf.baf7b0224a65bb4410556a85e0c4ec4d.txt' mode='r' encoding='UTF-8'>
[]
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/20_10x-2_jpg.rf.393bc59e55710fc46d73461977995643.txt' mode='r' encoding='UTF-8'>
['0 0.5218300653594772 0.2308056640625 0.007830882352941177 0.007626953125\n', '0 0.5590972222222222 0.264853515625 0.0036070261437908496 0.003740234375']
Old:
0 0.5218300653594772 0.2308056640625 0.007830882352941177 0.007626953125

['', '0 0.5590972222222222 0.264853515625 0.0036070261437908496 0.003740234375']
Old:
0 0.5590972222222222 0.264853515625 0.0036070261437908496 0.003740234375
New:
['0', '0.6412792968750001', '0.02970703124999996', '0.008623046875', '0.00748046875']
['', '0 0.6412792968750001 0.02970703124999996 0.008623046875 0.00748046875']
<_io.TextIOWrapper 

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/null2-2_20x-1_jpg.rf.0bab27e4aa58457fe3a36aa6c350ffe6.txt' mode='r' encoding='UTF-8'>
[]
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/27_20x-1_jpg.rf.bd6d3276a92a174a69ee51a22a3cad84.txt' mode='r' encoding='UTF-8'>
['0 0.7586846405228758 0.4467822265625 0.01380718954248366 0.0197607421875']
Old:
0 0.7586846405228758 0.4467822265625 0.01380718954248366 0.0197607421875
['']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/10_5x_JPG.rf.8e4b33ebc346e9b239618da0d82b44dc.txt' mode='r' encoding='UTF-8'>
[]
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/Flake5_10x_JPG.rf.b56fa89fca6ceec88f2a96c3b1571fed.txt' mode='r' encoding='UTF-8'>
['0 0.5201021241830065 0.296142578125 0.01579656862745098 0.02228515625\n', '0 0.5216013071895426 0.2747607421875 0.018790849673202614 0.0139013671875']
Old:
0 0.5201021241830065 0.296142578125 0.01579656862745098 0.02228515625

New:
['0', '0.5480566406249998', '0.09228515625', '0.

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/01_5x_JPG.rf.86bc5773026c52c47a6ed8bf5bb3bf38.txt' mode='r' encoding='UTF-8'>
['0 0.5150204248366013 0.4190771484375 0.021200980392156864 0.0071435546875']
Old:
0 0.5150204248366013 0.4190771484375 0.021200980392156864 0.0071435546875
New:
['0', '0.535908203125', '0.338154296875', '0.050683593750000006', '0.014287109375']
['0 0.535908203125 0.338154296875 0.050683593750000006 0.014287109375']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/-2_01_10x-2_jpg.rf.76d750d884b4a19f6a66c510369de852.txt' mode='r' encoding='UTF-8'>
['0 0.306858660130719 0.3501025390625 0.024056372549019607 0.015302734375']
Old:
0 0.306858660130719 0.3501025390625 0.024056372549019607 0.015302734375
New:
['0', '0.03351318359375002', '0.200205078125', '0.06702636718750005', '0.03060546875']
['0 0.03351318359375002 0.200205078125 0.06702636718750005 0.03060546875']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/07_5x-2_jpg.rf.e1ce1a3559b3028ed

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/flake12_5X-1_jpg.rf.eeb9afdff1798ec88ee07f2778c9c812.txt' mode='r' encoding='UTF-8'>
['0 0.42924836601307187 0.2460791015625 0.007426470588235294 0.00751953125']
Old:
0 0.42924836601307187 0.2460791015625 0.007426470588235294 0.00751953125
['']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/05_10x-1_jpg.rf.42fa5cb50d71682e7b5e50008e1316ae.txt' mode='r' encoding='UTF-8'>
['0 0.35429330065359477 0.3163720703125 0.01628267973856209 0.024296875\n', '0 0.3289828431372549 0.3468310546875 0.02400326797385621 0.017333984375']
Old:
0 0.35429330065359477 0.3163720703125 0.01628267973856209 0.024296875

New:
['0', '0.15166992187499995', '0.13274414062499995', '0.03892578125', '0.04859375']
['0 0.15166992187499995 0.13274414062499995 0.03892578125 0.04859375\n', '0 0.3289828431372549 0.3468310546875 0.02400326797385621 0.017333984375']
Old:
0 0.3289828431372549 0.3468310546875 0.02400326797385621 0.017333984375
New:
['0', '0.09116210

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/21_20x-2_jpg.rf.d0ef67056c7571c75cb1129c2db0d2e3.txt' mode='r' encoding='UTF-8'>
['0 0.259656862745098 0.772978515625 0.00701797385620915 0.0091015625']
Old:
0 0.259656862745098 0.772978515625 0.00701797385620915 0.0091015625
['']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/36-22_10x-2_jpg.rf.8fce9cc1bf6d87b41189fb59e7804520.txt' mode='r' encoding='UTF-8'>
['0 0.6209967320261438 0.4543505859375 0.015098039215686275 0.0163232421875']
Old:
0 0.6209967320261438 0.4543505859375 0.015098039215686275 0.0163232421875
New:
['0', '0.7892578125', '0.408701171875', '0.03609375', '0.032646484375']
['0 0.7892578125 0.408701171875 0.03609375 0.032646484375']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/flake8_10X_JPG.rf.ccdfe874968c8f43c9fb98115660a689.txt' mode='r' encoding='UTF-8'>
['0 0.5342156862745098 0.524921875 0.01937091503267974 0.0336474609375']
Old:
0 0.5342156862745098 0.524921875 0.01937091503267974 0.0336474

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/13_20X-1_jpg.rf.2df58f8903a684d5b13fa0e580a18f6b.txt' mode='r' encoding='UTF-8'>
['0 0.28971405228758174 0.505009765625 0.009681372549019608 0.0109130859375']
Old:
0 0.28971405228758174 0.505009765625 0.009681372549019608 0.0109130859375
['']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/03_10x_JPG.rf.8c04df7ba0a14dc90e5f77c1142b9b29.txt' mode='r' encoding='UTF-8'>
['0 0.5420915032679738 0.4265185546875 0.013639705882352941 0.0163427734375\n', '0 0.552953431372549 0.441015625 0.008876633986928105 0.007353515625\n', '0 0.5318504901960784 0.4114013671875 0.013933823529411764 0.0089990234375']
Old:
0 0.5420915032679738 0.4265185546875 0.013639705882352941 0.0163427734375

New:
['0', '0.600625', '0.353037109375', '0.032607421875', '0.032685546875']
['0 0.600625 0.353037109375 0.032607421875 0.032685546875\n', '0 0.552953431372549 0.441015625 0.008876633986928105 0.007353515625\n', '0 0.5318504901960784 0.4114013671875 0.0139

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/12_20X_JPG.rf.09299cadfb0808b5a08e8722c0b08efb.txt' mode='r' encoding='UTF-8'>
['0 0.5487459150326797 0.5134619140625 0.008741830065359477 0.0061181640625']
Old:
0 0.5487459150326797 0.5134619140625 0.008741830065359477 0.0061181640625
New:
['0', '0.6165332031249999', '0.5269238281249999', '0.020898437500000002', '0.012236328125']
['0 0.6165332031249999 0.5269238281249999 0.020898437500000002 0.012236328125']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/53_10x_JPG.rf.43aef29a3ec429769422002590e1c00e.txt' mode='r' encoding='UTF-8'>
['0 0.4989256535947712 0.5048388671875 0.009452614379084968 0.009970703125\n', '0 0.5346772875816994 0.4760302734375 0.003856209150326797 0.0051318359375']
Old:
0 0.4989256535947712 0.5048388671875 0.009452614379084968 0.009970703125

New:
['0', '0.4974316406249999', '0.5096777343750001', '0.02259765625', '0.01994140625']
['0 0.4974316406249999 0.5096777343750001 0.02259765625 0.01994140625\n'

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/flake11_5X_edge-path_3-1_jpg.rf.87546dd681d189418f4e3816a9a39563.txt' mode='r' encoding='UTF-8'>
[]
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/-03_01_10x-2_jpg.rf.45ba4495c1a8d9aa9a07814b672b3d7a.txt' mode='r' encoding='UTF-8'>
['0 0.35099264705882355 0.4957958984375 0.02979983660130719 0.0321533203125\n', '0 0.3395016339869281 0.556826171875 0.03593545751633987 0.0273681640625']
Old:
0 0.35099264705882355 0.4957958984375 0.02979983660130719 0.0321533203125

New:
['0', '0.14377929687500002', '0.491591796875', '0.071240234375', '0.064306640625']
['0 0.14377929687500002 0.491591796875 0.071240234375 0.064306640625\n', '0 0.3395016339869281 0.556826171875 0.03593545751633987 0.0273681640625']
Old:
0 0.3395016339869281 0.556826171875 0.03593545751633987 0.0273681640625
New:
['0', '0.11630859375000002', '0.6136523437500001', '0.085908203125', '0.054736328125']
['0 0.14377929687500002 0.491591796875 0.071240234375 0.0643066

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/flake12_5X_JPG.rf.6892751ccd85813ff003b230376fa222.txt' mode='r' encoding='UTF-8'>
['0 0.5037091503267973 0.44375 0.008398692810457516 0.0078515625']
Old:
0 0.5037091503267973 0.44375 0.008398692810457516 0.0078515625
New:
['0', '0.5088671874999997', '0.38749999999999996', '0.020078125', '0.015703125']
['0 0.5088671874999997 0.38749999999999996 0.020078125 0.015703125']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/flake12_10X-1_jpg.rf.a3867de64207e39b63f8e6de1a5f63a9.txt' mode='r' encoding='UTF-8'>
['0 0.4076021241830065 0.297109375 0.01310049019607843 0.0219921875']
Old:
0 0.4076021241830065 0.297109375 0.01310049019607843 0.0219921875
New:
['0', '0.27911132812499995', '0.09421875000000002', '0.031318359375', '0.043984375']
['0 0.27911132812499995 0.09421875000000002 0.031318359375 0.043984375']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/42_20x-1_jpg.rf.42a3ab5fec5f6037cb5eeb54336e00b2.txt' mode='r' encodi

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/flake10_5X_edge-path_2-1_jpg.rf.315eb256110c51467c7f2929b37950ec.txt' mode='r' encoding='UTF-8'>
[]
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/flake8_10X-1_jpg.rf.34536dd616c82599912269ae95650d94.txt' mode='r' encoding='UTF-8'>
['0 0.5685539215686274 0.8433935546875 0.025861928104575164 0.02328125']
Old:
0 0.5685539215686274 0.8433935546875 0.025861928104575164 0.02328125
['']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/09_20x_JPG.rf.de64800096fbe66065638ead312a6a25.txt' mode='r' encoding='UTF-8'>
['0 0.5304248366013072 0.50451171875 0.006217320261437909 0.00685546875\n', '0 0.5361070261437909 0.517099609375 0.01070669934640523 0.011083984375']
Old:
0 0.5304248366013072 0.50451171875 0.006217320261437909 0.00685546875

New:
['0', '0.572734375', '0.5090234375', '0.01486328125', '0.0137109375']
['0 0.572734375 0.5090234375 0.01486328125 0.0137109375\n', '0 0.5361070261437909 0.517099609375 0.0107066993464052

<_io.TextIOWrapper name='../Downloads/20x2/train/labels/12_10x-1_jpg.rf.40a3106e724776602eb0608a901a7063.txt' mode='r' encoding='UTF-8'>
['0 0.3165808823529412 0.466103515625 0.018856209150326795 0.009716796875']
Old:
0 0.3165808823529412 0.466103515625 0.018856209150326795 0.009716796875
New:
['0', '0.06151367187500001', '0.43220703125000004', '0.045078125', '0.01943359375']
['0 0.06151367187500001 0.43220703125000004 0.045078125 0.01943359375']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/flake10_5X_1_JPG.rf.c51a321c7f63f35edfaa05cde4d0f075.txt' mode='r' encoding='UTF-8'>
['0 0.5069281045751635 0.4458154296875 0.006486928104575164 0.0051416015625']
Old:
0 0.5069281045751635 0.4458154296875 0.006486928104575164 0.0051416015625
New:
['0', '0.5165625000000003', '0.391630859375', '0.0155078125', '0.010283203125']
['0 0.5165625000000003 0.391630859375 0.0155078125 0.010283203125']
<_io.TextIOWrapper name='../Downloads/20x2/train/labels/22_20x-1_jpg.rf.98c9dc558924d4653edb092c3e

In [5]:
#crops images and rewrites associated text files
#takes the first bounding box and chooses random boundaries that fully enclose the first bounding box
new_height = 640
new_width = 640

directory = "../Downloads/temp.v5i.yolov8/test"
files = os.listdir(directory + "/images")

for image_name in files:
    image_path = directory + "/images/" + image_name
    image = cv2.imread(image_path)
    old_height = image.shape[0]
    old_width = image.shape[1]
    print (old_height)
    print (old_width)
    #image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)\
    txt_path = directory + "/labels/" + image_name[:-3]+ "txt"
    file = open(txt_path, "r")
    boxes = file.readlines()
    #if no bounding boxes, just get the middle of the image
    if (len(boxes) == 0):
        left = int((old_width - new_width)/2)
        right = int((old_width + new_width)/2)
        top = int((old_height - new_height)/2)
        bottom = int((old_height + new_height)/2)
        cropped = image[top:bottom, left:right]
        cv2.imwrite(image_path, cropped)
    else:
        top_line = boxes[0]
        numbers = top_line.split()
        old_center_x = float(numbers[1])
        old_center_y = float(numbers[2])
        old_w = float(numbers[3])
        old_h = float(numbers[4])
        #get borders of bounding box in pixels on original image
        left_border = (old_center_x - old_w/2) * old_width
        right_border = (old_center_x + old_w/2) * old_width
        top_border = (old_center_y - old_h/2) * old_height
        bottom_border = (old_center_y + old_h/2) * old_height
        #get new image borders in pixels on original image
        new_left = random.randint(max(0,int(right_border - new_width)), min(int(left_border), old_width - new_width))
        new_right = new_left + new_width
        new_top = random.randint(max(0,int(bottom_border - new_height)),min(int(top_border), old_height - new_height))
        new_bottom = new_top + new_height
        print(f"Left: {new_left}")
        print(f"Right: {new_right}")
        print(f"top: {new_top}")
        print(f"Bottom: {new_bottom}")
        image = image[new_top:new_bottom,new_left:new_right]
        cv2.imwrite(image_path, image)
        new_h = old_h * old_height/new_height
        new_w = old_w * old_width/new_width
        new_x = float((old_center_x * old_width - new_left)/new_width)
        new_y = float((old_center_y * old_height - new_top)/new_height)
        numbers[1] = str(new_x)
        numbers[2] = str(new_y)
        numbers[3] = str(new_w)
        numbers[4] = str(new_h)
        boxes[0] = numbers[0]+ " " + numbers[1] + " " + numbers[2] + " " + numbers[3] + " " + numbers[4]
        if len(boxes) > 1:
            boxes[0] += '\n'
    line = 1
    while (line < len(boxes)):
        numbers = boxes[line].split()
        #class_id center_x center_y width height - format of each line
        #calculate new numbers, write it into array
        old_center_x = float(numbers[1])
        old_center_y = float(numbers[2])
        old_w = float(numbers[3])
        old_h = float(numbers[4])
        # boundaries in pixels of box on old image
        left = (old_center_x - old_w/2) * old_width
        right = (old_center_x + old_w/2) * old_width
        top = (old_center_y - old_h/2) * old_height
        bottom = (old_center_y + old_h/2) * old_height
        new_center_x = float((old_center_x * old_width - new_left)/new_width)
        new_center_y = float((old_center_y * old_height - new_top)/new_height)
        if (new_center_x < 0 or new_center_y < 0 or new_center_x > 1 or new_center_y > 1):
            boxes[line] = ''
        else:
            height_scale = old_height/new_height
            width_scale = old_width/new_width
            new_h = old_h * height_scale
            new_w = old_w * width_scale
            if (new_center_x - new_w < 0):
                old_w = new_w
                old_centerx = new_center_x
                new_w = old_centerx + old_w/2
                new_center_x = new_w/2
            if (new_center_x + new_w > 1):
                old_w = new_w
                old_centerx = new_center_x
                new_w = 1-old_centerx + old_w/2
                new_center_x = (1 - new_w/2)
            if (new_center_y - new_h < 0):
                old_h = new_h
                old_centery = new_center_y
                new_h = old_centery + old_h/2
                new_center_y = new_h/2
            if (new_center_y + new_h > 1):
                old_h = new_h
                old_centery = new_center_y
                new_h = (1-old_centery) + old_h/2
                new_center_y = (1 - new_h/2)
            numbers[1] = str(new_center_x)
            numbers[2] = str(new_center_y)
            numbers[3] = str(new_w)
            numbers[4] = str(new_h)
            boxes[line] = numbers[0]+ " " + numbers[1] + " " + numbers[2] + " " + numbers[3] + " " + numbers[4]
            if len(boxes) > 1 and line < len(boxes) - 1:
                boxes[line] += '\n'
        line +=1
    file.close()
    file = open(txt_path, "w")
    file.writelines(boxes)
    file.close()
    #pull up the text file
    #write it

2048
2448
Left: 906
Right: 1546
top: 476
Bottom: 1116
2048
2448
Left: 452
Right: 1092
top: 412
Bottom: 1052
2048
2448
Left: 758
Right: 1398
top: 798
Bottom: 1438
2048
2448
Left: 1441
Right: 2081
top: 1032
Bottom: 1672
2048
2448
Left: 820
Right: 1460
top: 919
Bottom: 1559
2048
2448
Left: 1761
Right: 2401
top: 377
Bottom: 1017
2048
2448
Left: 487
Right: 1127
top: 351
Bottom: 991
2048
2448
Left: 1157
Right: 1797
top: 759
Bottom: 1399
2048
2448
Left: 936
Right: 1576
top: 94
Bottom: 734
2048
2448
Left: 1504
Right: 2144
top: 1197
Bottom: 1837
2048
2448
Left: 868
Right: 1508
top: 590
Bottom: 1230
2048
2448
Left: 605
Right: 1245
top: 335
Bottom: 975
2048
2448
Left: 916
Right: 1556
top: 905
Bottom: 1545
2048
2448
Left: 685
Right: 1325
top: 162
Bottom: 802
2048
2448
Left: 778
Right: 1418
top: 162
Bottom: 802
2048
2448
Left: 361
Right: 1001
top: 410
Bottom: 1050
2048
2448
Left: 284
Right: 924
top: 527
Bottom: 1167
2048
2448
Left: 634
Right: 1274
top: 551
Bottom: 1191
2048
2448
Left: 1113
Right: 1

In [69]:
#change hue using pytorch
import time
start = time.time()
image = torchvision.io.read_image("Images/WS2_112723_07112024/17_10x.JPG")
image = transforms.functional.adjust_hue(image, 0.13)
#image = transforms.functional.adjust_contrast(image, 1.1)
image = transforms.v2.functional.to_dtype(image, dtype = torch.uint8, scale = True)
torchvision.io.write_jpeg(image,'test.jpg')
end = time.time()
print(end - start)

1.2266027927398682


In [127]:
#change hue using open CV
import time
start = time.time()
image = cv2.imread("Images/WS2_112723_07112024/17_10x.JPG")
image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
print(image)
image = image.astype(np.uint32)
image[:,:,0] += 23
image[:,:,0] = image[:,:,0]%180
image = image.astype(np.uint8)
image = cv2.cvtColor(image, cv2.COLOR_HSV2BGR)
cv2.imwrite('test.jpg', image)
end = time.time()
print(end - start)

[[[ 24  28  46]
  [ 11  57  63]
  [  4  83  86]
  ...
  [109  54  38]
  [115  41  37]
  [114  34  37]]

 [[ 36  27  48]
  [ 14  54  61]
  [  8  89  77]
  ...
  [109  50  41]
  [115  38  40]
  [114  33  39]]

 [[ 55  35  44]
  [ 21  44  58]
  [ 11  91  76]
  ...
  [109  49  42]
  [109  50  41]
  [109  50  41]]

 ...

 [[103  51  35]
  [103  51  35]
  [109  60  34]
  ...
  [ 63  80  32]
  [ 63  82  31]
  [ 57  90  31]]

 [[ 96  43  30]
  [103  51  35]
  [109  58  35]
  ...
  [ 55  57  27]
  [ 55  59  26]
  [ 56  66  31]]

 [[ 96  41  31]
  [ 96  41  31]
  [109  62  33]
  ...
  [ 50  29  26]
  [ 55  53  29]
  [ 55  53  29]]]
0.23402118682861328
